# Generated by Django 5.0.3 on 2024-04-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
